export const FETCH_HEROS_LIST = 'FETCH/HEROS_LIST';
export const FETCH_HEROS_LIST_SUCCESS = 'FETCH/HEROS_LIST/SUCCESS';
export const FETCH_HEROS_LIST_ERROR = 'FETCH/HEROS_LIST/ERROR';

export const FETCH_HERO_PROFILE = 'FETCH/HERO_PROFILE';
export const FETCH_HERO_PROFILE_SUCCESS = 'FETCH/HERO_PROFILE/SUCCESS';
export const FETCH_HERO_PROFILE_ERROR = 'FETCH/HERO_PROFILE/ERROR';

export const EDIT_HERO_PROFILE = 'EDIT/HERO_PROFILE';
export const EDIT_HERO_PROFILE_SUCCESS = 'EDIT/HERO_PROFILE/SUCCESS';
export const EDIT_HERO_PROFILE_ERROR = 'EDIT/HERO_PROFILE/ERROR';
